import Head from "next/head";
import { Fragment } from "react";

import Navigation from "@/components/Layout/Navigation";
import FormContainer from "@/components/UI/FormContainer";
import Form from "@/components/Form/Form";
import ToDoList from "@/components/ToDo/ToDoList";
import { ToDoItem } from "@/types/todo";
import { ListProps } from "@/types/todo";
import { fetchToDos } from "@/util/fetchToDos";

export default function Home(props: ListProps) {
  const DUMMY_TODOS: ToDoItem[] = [
    {
      id: 1,
      userId: 1,
      title: "TEST",
      completed: true,
    },
    {
      id: 2,
      userId: 1,
      title: "SECOND_TEST",
      completed: false,
    },
    {
      id: 3,
      userId: 1,
      title: "THIRD_TEST",
      completed: true,
    },
  ];
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <section className="d-flex justify-content-center pt-5 flex-row">
        <FormContainer>
          <Form></Form>
        </FormContainer>
      </section>
      <section className="d-flex justify-content-center pt-5 flex-row">
        <FormContainer>
          <ToDoList ToDoItems={props.todos} />
        </FormContainer>
      </section>
    </Fragment>
  );
}

export async function getServerSideProps() {
  const toDoList = await fetchToDos();
  return {
    props: {
      todos: toDoList,
    },
  };
}
